- name: Clone NG-GL4ES
  run: |
    git clone --recursive https://github.com/BZLZHH/NG-GL4ES.git

- name: Build arm64
  run: |
    cd NG-GL4ES
    mkdir build
    cd build

    cmake .. \
      -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
      -DANDROID_ABI=arm64-v8a \
      -DANDROID_PLATFORM=android-24

    make -j$(nproc)
